name: Repository Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Create backup directory
        run: |
          mkdir -p .backup
          
      - name: Create backup
        run: |
          # Create timestamp for backup name
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          BACKUP_NAME="backup_${TIMESTAMP}.tar.gz"
          
          # Create backup archive of the entire repository
          git bundle create .backup/${BACKUP_NAME} --all
          
          # Keep only the last 7 backups
          cd .backup
          ls -t backup_*.tar.gz | tail -n +8 | xargs -r rm
          
          # Add .backup to git if not already tracked
          git add .backup/${BACKUP_NAME}
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git commit -m "Automated backup ${TIMESTAMP}"
          git push
