name: Copy Main Branch

on:
  workflow_dispatch:

jobs:
  copy-main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Clone source repository main branch
        run: |
          git clone -b main --single-branch https://${{ secrets.BACKUP_PAT }}@github.com/cavort-konzepte-gmbh/pv-corr.git source-repo

      - name: Clone destination repository
        run: |
          git clone -b main --single-branch https://${{ secrets.BACKUP_PAT }}@github.com/cvrt-jh/pv-corr.git dest-repo

      - name: Copy files preserving .bolt
        run: |
          cd source-repo
          # Copy all files except .git
          find . -mindepth 1 ! -regex '^.*/\.git.*' -exec cp -r --parents {} ../dest-repo/ \;
          cd ../dest-repo
          # Stage all changes but preserve .bolt
          git add .
          # Restore .bolt directory if it was deleted
          git checkout main -- .bolt || true
          git commit -m "Update from source repository"
          git push origin main

      - name: Cleanup
        if: always()
        run: |
          rm -rf source-repo dest-repo
